### ISSUE TITLE
Cannot execute binary on macos 12 Monterey

### ISSUE THREAD

**Issue by wndhydrnt** [GoogleContainerTools/container-structure-test#286] opened 2021-10-29 11:31 UTC
On a workstation that runs macos 12 Monterey, container-structure-test [v1.10.0](https://github.com/GoogleContainerTools/container-structure-test/releases/tag/v1.10.0) fails with the following error:

```
$ ./container-structure-test
fatal error: runtime: bsdthread_register error

runtime stack:
runtime.throw(0x160121c, 0x21)
        /usr/local/go/src/runtime/panic.go:605 +0x95 fp=0x7ff7bfeff3d0 sp=0x7ff7bfeff3b0 pc=0x102a1b5
runtime.goenvs()
        /usr/local/go/src/runtime/os_darwin.go:108 +0x83 fp=0x7ff7bfeff400 sp=0x7ff7bfeff3d0 pc=0x1027a53
runtime.schedinit()
        /usr/local/go/src/runtime/proc.go:492 +0xa4 fp=0x7ff7bfeff440 sp=0x7ff7bfeff400 pc=0x102cb94
runtime.rt0_go(0x7ff7bfeff470, 0x1, 0x7ff7bfeff470, 0x1000000, 0x1, 0x7ff7bfeff690, 0x0, 0x7ff7bfeff6a9, 0x7ff7bfeff867, 0x7ff7bfeff893, ...)
        /usr/local/go/src/runtime/asm_amd64.s:175 +0x1eb fp=0x7ff7bfeff448 sp=0x7ff7bfeff440 pc=0x105452b
```

I was able to trace this down to the version of Go that is being used to build the binaries. Go 1.9 and 1.10 produce the error above. A binary built by a newer release, e.g. 1.17, does not.

**Comment by nkubala** [comment] 2021-11-09 18:31
hey @wndhydrnt and everyone, I just released v1.11.0 which (hopefully) has fixed this issue: https://github.com/GoogleContainerTools/container-structure-test/releases/tag/v1.11.0

would one of you mind confirming that things look good in this release? I've marked it as a pre-release until I can verify things are working as intended (I don't have a machine running macOS Monterey yet so I can't test myself 😅 )

**Comment by wndhydrnt** [comment] 2021-11-10 07:02
Hey @nkubala, I can confirm that v1.11.0 works on macos 12 Monterey. Many thanks for getting this fixed.

**Comment by nkubala** [comment] 2021-11-10 18:13
@wndhydrnt great to hear!

**Closed by nkubala** 2021-11-10 18:13 UTC
