### ISSUE TITLE
ERROR - field unboundEnv not found in type v2.MetadataTest

### ISSUE THREAD

**Issue by cavo789** [GoogleContainerTools/container-structure-test#313] opened 2022-10-03 07:57 UTC
Hello

Just trying your tool; thanks for it.

I think there is a problem with the `unboundEnv` feature; seems inexisting:

```yaml
schemaVersion: "2.0.0"
metadataTest:
  unboundEnv:
    - key: "PRIVATE_TOKEN"
```

```bash
=== RUN:
--- FAIL
duration: 0s
Error: error parsing config file: error unmarshalling config: yaml: unmarshal errors:
  line 17: field unboundEnv not found in type v2.MetadataTest
```

The documentation needs perhaps to be updated: https://github.com/GoogleContainerTools/container-structure-test#metadata-test

Thanks

**Comment by bananaappletw** [comment] 2022-10-16 05:27
@nkubala Could you make a new release? The issue is already fixed on current master branch. Thank you.

**Closed** 2023-03-14 00:45 UTC
