### ISSUE TITLE
Config file validation does not set failure exit code

### ISSUE THREAD

**Issue by xingao267** [GoogleContainerTools/container-structure-test#146] opened 2018-06-05 19:00 UTC
I'm having this invalid config yaml file:

schemaVersion: "2.0.0"

commandTests:
- name: 'path-envvar'
  command: ['sh', '-c', 'echo $PATH']
  expectedOutput: ['/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin']

metadataTest:
  entrypoint: ['bazel']

And here is my command:

container-structure-test test --driver docker --image toolchain:intermediate --config container/ubuntu16_04/bazel/container.yaml

The output is 

\=======================================
\====== Test file: container.yaml ======
\=======================================

ERROR: Please provide a valid Command to run for test path-envvar 
=== RUN: Metadata Test
--- PASS

\=======================================
\=============== RESULTS ===============
\=======================================
Passes:      1
Failures:    0
Total tests: 1

PASS

It treats the whole test as a PASS, and the exit code is

$ echo $?
0

It causes the container_test wrapper in rules_docker to show it as a passing test as well. It seems problematic.

**Comment by xingao267** [comment] 2018-06-05 19:32
It happens with https://github.com/bazelbuild/rules_docker/pull/416

**Comment by nkubala** [comment] 2018-06-05 20:33
Hey @xingao267, thanks for reporting. The reason this is failing to parse is because in schema version 2.0.0, we changed the `command` to be a single string, with a list of `args` passed in addition. Changing this to 
```
command: 'sh'
args: ['-c', 'echo $PATH']
```
should work.

However, this shouldn't be marking the test run as a `PASS`, so I'm looking into that now.

Just a side note, this will be much easier to do through the MetadataTest when https://github.com/GoogleContainerTools/container-structure-test/issues/145 is fixed.

**Comment by xingao267** [comment] 2018-06-12 18:32
The tests still pass when yaml parsing fails:

I'm running this:

container-structure-test test --driver docker --image containerubuntu16_04buildersrbe-ubuntu16_04toolchain:intermediate --config container/common/go.yaml --config container/ubuntu16_04/ubuntu16_04.yaml

container/common/go.yaml invalid yaml syntax, and the test output is this:

$ container-structure-test test --driver docker --image containerubuntu16_04buildersrbe-ubuntu16_04toolchain:intermediate --config container/common/go.yaml --config container/ubuntu16_04/ubuntu16_04.yaml 
================================
====== Test file: go.yaml ======
================================

ERROR: Error parsing config file: yaml: line 17: mapping values are not allowed in this context 
=========================================
====== Test file: ubuntu16_04.yaml ======
=========================================

INFO: stdout: Ubuntu 16.04.4 LTS
                  
=== RUN: Command Test: os-version
--- PASS
stdout: Ubuntu 16.04.4 LTS

=========================================
================ RESULTS ================
=========================================
Passes:      1
Failures:    0
Total tests: 1

PASS

It treat the whole test as PASS.
@nkubala

**Comment by xingao267** [comment] 2018-06-14 16:56
@nkubala @tejal29 friendly ping~

**Comment by nkubala** [comment] 2018-06-14 17:30
Are you still seeing this at HEAD? I haven't done a release with the fix yet so if you're using the most recent binary you'll still see the issue. I'll get a release out today.

**Comment by xingao267** [comment] 2018-06-14 18:19
Yes. it is failing with binary built from HEAD.

**Comment by nkubala** [comment] 2018-06-20 17:48
@xingao267 I'm unable to reproduce this. Building from master, I see
```
➜  container-structure-test git:(master) ./out/container-structure-test test --image test_container:latest --config ~/Development/sandbox/container.yaml
=======================================
====== Test file: container.yaml ======
=======================================

=== RUN: path-envvar
--- FAIL
Error: Please provide a valid command to run for test path-envvar
=== RUN: Metadata Test
--- PASS
ERROR: FAIL

=======================================
=============== RESULTS ===============
=======================================
Passes:      1
Failures:    1
Total tests: 2

FAIL
```

It looks like you're getting a different error now though: `ERROR: Error parsing config file: yaml: line 17: mapping values are not allowed in this context`. Did you change something in your config?

**Comment by xingao267** [comment] 2018-06-20 17:53
@nkubala Yes. I'm getting an error which occurs when the yaml format is invalid. You can try adding this snippet in your yaml file:

metadataTest:
  env:
    -key: 'PATH'
     value: '/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/opt/python3.6/bin:/usr/local/go/bin'

**Comment by xingao267** [comment] 2018-06-25 17:28
@nkubala Friendly ping~ rules_docker's container_test depends on this. This makes both invoking the binary directly or through container_test gives false negative test results.

**Comment by nkubala** [comment] 2018-06-25 18:44
@xingao267 sorry for the delay. I see your problem now: running the invalid yaml by itself will cause the test run to fail (which is the repro I was getting and why I was confused), but running it with another config file that does exit successfully causes the test runner to think everything passed. Looking into a fix for this.

**Comment by xingao267** [comment] 2018-06-25 20:45
Thanks for looking into a fix!

Actually, even with the following single broken yaml file, this would pass:

```
schemaVersion: "2.0.0"

commandTests:
- name: 'check-openssl'
  command: 'openssl'
  args: ['version']
  expectedOutput: ['OpenSSL .*']

fileExistenceTests:
- name: 'OpenJDK'
  isDirectory: true
  path: '/usr/lib/jvm/java-8-openjdk-amd64'
  shouldExist: true

  env:
    - key: 'JAVA_HOME'
      value: '/usr/lib/jvm/java-8-openjdk-amd64'

```
where I'm missing the "metadataTest:" above "env:" Also I think fileExistenceTests no longer take isDirectory key, but it didn't complain about either, just simply ignored the errors.

**Comment by nkubala** [comment] 2018-06-27 00:15
Ok, I actually think I figured this out now haha. The underlying issue was with the strict unmarshalling we were doing for the configs, which was correct except we weren't checking the error so any parsing errors were thrown away silently. #154 should fix that issue, causing this malformed config to fail. The `isDirectory` key change should also be addressed by this change.

**Comment by xingao267** [comment] 2018-06-27 19:37
@nkubala Thanks! I just tried it out. It works fine with one yaml file. But with multiple yaml files, if one or some of them has broken yaml, the test still passes.

**Comment by nkubala** [comment] 2018-06-27 20:00
@xingao267 yep sorry, https://github.com/GoogleContainerTools/container-structure-test/pull/153 didn't get merge yet but this issue got closed automatically.

**Comment by nkubala** [comment] 2018-06-27 22:04
sorry, I need to stop typing "Fixes <issue>" in my PRs haha. can you build from HEAD now and try this again?

**Closed** 2018-06-27 22:03 UTC

**Comment by xingao267** [comment] 2018-06-28 00:07
No worries! I just tried, and my tests failed properly!
